# FROM --platform=$TARGETPLATFORM rust
FROM rust:alpine
WORKDIR /app
RUN apk add --no-cache cmake pkgconfig libressl-dev git clang clang-dev musl-dev
RUN rustup update && \
  rustup default nightly && \
  rustup update nightly && \
  rustup target add wasm32-unknown-unknown && \
  cargo install cargo-chef 